#dockerfile for solver
FROM archlinux:base-devel
COPY . /xorricane
RUN pacman -Syu --noconfirm && pacman -Syu --noconfirm base-devel jemalloc gcc-libs benchmark boost catch2 cmake git && cd xorricane && cmake . && make xorricane
ENTRYPOINT [ "xorricane/xorricane" ]

#
# build image with
#   docker build -t xorricane:0.1 .
# solve instance at path/fname with
#   docker run -v path/fname:path/fname 2xnf_solver_docker path/fname [args]
# or use docker_solve.sh
# 
