#dockerfile for solver
FROM archlinux:base-devel
COPY . /xnf_cdcl_solver
RUN pacman -Syu --noconfirm && pacman -Syu --noconfirm base-devel jemalloc gcc-libs benchmark boost catch2 cmake git && cd xnf_cdcl_solver && cmake . && make xnf_cdcl_solver
ENTRYPOINT [ "xnf_cdcl_solver/xnf_cdcl_solver" ]

#
# build image with
#   docker build -t xnf_cdcl_solver:0.1 .
# solve instance at path/fname with
#   docker run -v path/fname:path/fname 2xnf_solver_docker path/fname [args]
# or use docker_solve.sh
# 
